"""
Code Generation Templates

Jinja2-style templates for generating models, schemas, routers, migrations.
"""

# ============================================================================
# Database Model Template
# ============================================================================

MODEL_TEMPLATE = '''"""
{name} Database Model

Auto-generated by VelvetEcho CLI
"""

from sqlalchemy import Column, String, Text, Integer, Float, Boolean, DateTime, JSON
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from velvetecho.database import BaseModel, TimestampMixin, SoftDeleteMixin


class {name}(BaseModel{mixins}):
    """
    {name} database model

    Auto-generated CRUD endpoints:
    - GET    /api/{table_name}
    - GET    /api/{table_name}/{{id}}
    - POST   /api/{table_name}
    - PUT    /api/{table_name}/{{id}}
    - DELETE /api/{table_name}/{{id}}
    """

    __tablename__ = "{table_name}"

{fields}
'''

# ============================================================================
# Pydantic Schemas Template
# ============================================================================

SCHEMAS_TEMPLATE = '''"""
{name} Pydantic Schemas

Auto-generated by VelvetEcho CLI
"""

from uuid import UUID
from datetime import datetime
from typing import Optional
from pydantic import BaseModel


class {name}Create(BaseModel):
    """Schema for creating {name}"""

{create_fields}


class {name}Update(BaseModel):
    """Schema for updating {name}"""

{update_fields}


class {name}Response(BaseModel):
    """Schema for {name} response"""

{response_fields}

    class Config:
        from_attributes = True
'''

# ============================================================================
# API Router Template
# ============================================================================

ROUTER_TEMPLATE = '''"""
{name} API Router

Auto-generated by VelvetEcho CLI
"""

from uuid import UUID
from fastapi import APIRouter, Depends
from sqlalchemy.ext.asyncio import AsyncSession

from velvetecho.database import Repository, get_session
from velvetecho.database.models.{name_lower} import {name}
from velvetecho.models.{name_lower} import {name}Create, {name}Update, {name}Response
from velvetecho.api import StandardResponse
from velvetecho.api.crud_router import CRUDRouter
from velvetecho.api.exceptions import NotFoundException

# Router configuration (used by auto-discovery)
PREFIX = "{prefix}"
TAGS = ["{tags}"]

# ============================================================================
# Repository
# ============================================================================


class {name}Repository(Repository[{name}]):
    """Repository for {name} with custom methods"""

    pass  # Add custom query methods here


# ============================================================================
# Router Setup
# ============================================================================

router = APIRouter()


def get_{name_lower}_repository(session: AsyncSession = Depends(get_session)):
    return {name}Repository(session, {name})


# ============================================================================
# Auto-Generated CRUD Routes
# ============================================================================

crud_router = CRUDRouter(
    model={name},
    create_schema={name}Create,
    update_schema={name}Update,
    response_schema={name}Response,
    prefix="",
    get_repository=get_{name_lower}_repository,
)

router.include_router(crud_router.router)

# ============================================================================
# Custom Routes
# ============================================================================

# Add your custom endpoints here
# Example:
#
# @router.get("/{{id}}/statistics", response_model=StandardResponse[dict])
# async def get_{name_lower}_stats(
#     id: UUID,
#     repo: {name}Repository = Depends(get_{name_lower}_repository),
# ):
#     """Get {name_lower} statistics"""
#     {name_lower} = await repo.get_by_id(id)
#
#     if not {name_lower}:
#         raise NotFoundException("{name}", id)
#
#     return StandardResponse(
#         data={{"TODO": "compute stats"}},
#         message="Statistics retrieved",
#     )
'''.replace("{name_lower}", "{name}".lower())

# ============================================================================
# Alembic Migration Template
# ============================================================================

MIGRATION_TEMPLATE = '''"""
Create {table_name} table

Auto-generated by VelvetEcho CLI
Revision ID: {timestamp}
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql as sa_uuid


# revision identifiers
revision = '{timestamp}'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    """Create {table_name} table"""
    op.create_table(
        '{table_name}',
{columns}
    )


def downgrade():
    """Drop {table_name} table"""
    op.drop_table('{table_name}')
'''
